### Localhost
POST localhost:8080/v1/chat/completions
Content-Type: application/json

{
  "Model": "gpt-3.5-turbo",
  "Messages": [
    {
      "Role": "user",
      "Content": "Hello World!"
    }
  ]
}

### Localhost
GET localhost:8080/v1/chat/completions


### Localhost: stream
POST localhost:8080/v1/chat/completions
Content-Type: application/json

{
  "Model": "gpt-3.5-turbo",
  "Messages": [
    {
      "Role": "user",
      "Content": "Hello World!"
    }
  ],
  "Stream": true
}
